### ISSUE TITLE
feat(rln-relay): v0.14.0 Release 

### ISSUE THREAD

**Issue by rymnc** [status-im/nwaku#1376]
### Problem
This is to keep track of the rln-relay features to be ready for integration in the next nwaku release 0.14.0.

- [ ] Key store for RLN credential management (@s1fr0)
  - [ ] https://github.com/vacp2p/rfc/issues/543
  - [ ] https://github.com/status-im/nwaku/issues/1238
  - [ ] https://github.com/status-im/nwaku/issues/1278
  
- [ ] Better error handling by rln-relay (@rymnc)
  - [ ] https://github.com/status-im/nwaku/issues/1245

- [ ] https://github.com/vacp2p/rln-contract/issues/10 (@staheri14)
- [ ] https://github.com/status-im/nwaku/issues/1270

- [ ] Refactoring to clean up rln-relay
  - [ ] https://github.com/status-im/nwaku/issues/1370 
  - [ ] https://github.com/status-im/nwaku/issues/1369

- [ ] Improve robustness of rln-relay
  - [ ] Handle chain forking re: registrations - https://github.com/status-im/nwaku/issues/1338 (@rymnc)
  - [ ] Manage reconnections to the eth node - https://github.com/status-im/nwaku/issues/1306 (@rymnc)
 
- [ ] General maintenance
  - [ ] https://github.com/status-im/nwaku/issues/1358 (@rymnc)

There are a couple of other low-hanging fruits which we can attempt in case the above list is completed earlier than the deadline.

## Acceptance criteria

Getting the listed features ready and tested by the indicated deadline below.
Making sure there is no regression regarding the added features on the waku v2 fleets.

## Deadline
December 8 (one week prior to the next release date)

cc: @jm-clius @oskarth

**Comment by staheri14** [comment]
Following our call today with @LNSD and @s1fr0 (and another call with @rymnc), below are a set of refactoring tasks to be tackled (from https://notes.status.im/oozxlJl4QSiEhADbzTEXxA?view):

**Tasks that can be attacked independently**
The tasks of this section have no specific dependency on other refactoring tasks, so they can be done in parallel or in any desired order. 
- [ ] Static rln lib compilation (Ind)
    - https://github.com/status-im/nwaku/issues/1380
- [ ] CI feature flagged jobs/checks (Ind)
- [ ] RLN [Barrel imports](https://basarat.gitbook.io/typescript/main-1/barrel) (Ind)
    - WIP in here: https://github.com/status-im/nwaku/pull/1379

**Tasks with dependency**
The tasks listed here should be tackled in the same order they appear below. This is to minimize the code conflicts and have a speedy development and PR review process. 
- [ ] 1. Code split: Split dynamic and static mounting in different modules  (@staheri14)
    - Move static mounting constants to the static mounting module (e.g., mimic message store)
    ```
    - RLN.nim (barrel import)
    - RLN/
        - STATIC MOUNT.nim (barrel import)
        - STATIC MOUNT/
            - constants.nim
            - logic.nim
        - DYNAMIC MOUNT.nim (barrel import)
        ...
    ```
- [ ] 2. Code split: Split protocol metrics into a module (mimic other protocols) (@rymnc)
- [ ] 3. Make the protocol follow the other protocols' mounting pattern (@rymnc)
    - WIP in here: https://github.com/status-im/nwaku/pull/1379
- [ ] 4. Extract group manager interface from waku RLN relay (this one is already captured in the issue description but replicated here to indicate it has a dependency on the above refactoring tasks)


As discussed in the call, please tackle each one in a single PR and keep PRs self-contained.

Any comments?

**Comment by LNSD** [comment]
> Any comments?

One little comment 😁 

As we discussed, the listed tasks correspond to the first part of the refactoring effort; it is very likely that as these tasks progress and the code changes are reviewed, we will better understand the remaining work, and we'll be in the position to plan and prioritize the second part.

**Comment by staheri14** [comment]
> it is very likely that as these tasks progress and the code changes are reviewed,

Correct! it is just the first cut, the list may evolve as we progress. cc: @rymnc @s1fr0

**Comment by staheri14** [comment]
I see there are some updates on the issue description e.g., the deadline. It would be great if after each update we add a comment to this issue and announce it so that the integrated changes get attention.

**Comment by LNSD** [comment]
Adding the following task/PR to the list:

- [ ] Decouple the Waku message type from RLN types. Break a dependency loop.
	+ #1399

**Comment by LNSD** [comment]
> @s1fr0 and I have discussed that we are moving the following sections to the next release -
> 
> * wallet integration into rln-relay
> * robustness of rln-relay
> * redeploy rln-contract
>   The v0.15.0 issue will include them

Please, update this issue description accordingly.

We can also file a v0.15.0 issue containing those items (up to you).

**Comment by rymnc** [comment]
Updated the issue description. I'll create the v0.15.0 issue soon :)

**Comment by rymnc** [comment]
Created the v0.15.0 issue - https://github.com/waku-org/nwaku/issues/1486

**Comment by rymnc** [comment]
If it looks okay to @s1fr0, we can close it!
