### ISSUE TITLE
`nwaku` for operators trial

### ISSUE THREAD

**Issue by jm-clius** [status-im/nwaku#828]
# Background

One of the main takeaways from the [Q4 2022 Vac Sustainability and Business Workshop](https://forum.vac.dev/t/vac-sustainability-and-business-workshop/116#q1-goals-draft-37) was _the need for `nwaku` to settle into a niche of being an easy-to-install, easy-to-monitor, lightweight and robust option for user-run Waku v2 nodes._

Currently the main obstacles to achieving this goal is:
- incomplete or unclear documentation for users on how to set up and dimension their own `nwaku` nodes for different protocols
- limited pre-compiled binaries for easy setup (users usually need to clone the repo and build `nwaku` themselves, seldomly a smooth process)
- limited insight into actual robustness of running a `nwaku` node in the long term, especially for lesser-used protocols, such as `filter` and `lightpush`
- limited visibility (e.g. a metric) of the number of user-run nodes in the default Waku v2 network and number of applications using Waku v2
- lack of ambient peer discovery

# What do we want to achieve as a first step?

This issue tracks the work necessary to launch a Vac-internal operator-run node trial. Specifically, we want:

## Goal 1: Team-internal operators set up own `nwaku` nodes

Operators to follow instructions to set up their own `nwaku` node using a precompiled binary that:
- participates and is discoverable in the default `relay` network
- provides a dimensioned `store`
- provide `lightpush` and `filter` capabilities

Between team members we could probably run a hybrid network of nodes on at least Windows, Linux and MacOS.

## Goal 2: Operators monitor their nodes

Operators to follow instructions to monitor their nodes, e.g. using an included metrics dashboard, looking at logs, etc.

## Goal 3: Operators to provide informal, weekly updates

This should track two main qualitative metrics:
1. "How easy is it to operate a node?"
- feedback on documentation/instructions. What are the gaps in knowledge that should be bridged/obscured from end users?
- are the included tooling enough for operation?
- feedback re available metrics/logs and their usefulness
- feedback re metrics dashboard
2. "How well does the node run?"
- i.e. how stable has it been running as far as you can tell from metrics/logs
- how many stable connections does the node maintain
- how many new, useful peers has the node discovered (only PX during trial)

As a team we can use the various `chat2` clients to simulate different scenarios during the trial, to ensure we properly test `filter`, `lightpush`, etc.

# What do we have already?

- Some scattered documentation on how to build and run a `nwaku` node from source code with default config, e.g. [here](https://github.com/status-im/nwaku) and [here](https://github.com/status-im/nwaku/blob/master/docs/tutorial/dingpu.md)
- A basic [Dockerfile](https://github.com/status-im/nwaku/blob/master/Dockerfile) to build a deployable image
- Ubuntu and MacOS binaries included as [release assets](https://github.com/status-im/nwaku/releases)

# What still needs to be done?

At minimum, before launching trial:
- [ ] Distributable `nwaku` binaries available for all major OSs and architectures: https://github.com/status-im/nwaku/issues/611
- [ ] Published all-in-one docker image, including some tooling for monitoring: https://github.com/status-im/nwaku/issues/737
- [x] Minimal ambient peer discovery: GossipSub peer exchange: https://github.com/status-im/nim-libp2p/pull/647
- [x] Basic documentation on how to run and monitor a `nwaku` node from scratch. We could use the [The Nimbus Book](https://nimbus.guide/) as inspiration here.
- [ ] Operator-focused metrics (e.g. number of content topics in use, current message rate, updated dashboards, etc.)

Nice to haves before trial launch:
- [ ] Proper `nwaku` resource management: https://github.com/status-im/nwaku/issues/798 (especially if we're going to add more resources, such as a Grafana dashboard)
- [ ] Ability to mark messages as "do not store": https://github.com/vacp2p/rfc/issues/441
- [x] Support for DNS addresses: https://github.com/status-im/nwaku/issues/521
- [x] Solution for the `store` timestamping and indexing issue, under discussion [here](https://forum.vac.dev/t/timestamping-and-indexing-in-the-wakustore/118)
- [ ] Document `nodekey` generation: https://github.com/status-im/nwaku/issues/847

cc @oskarth @staheri14 @kaiserd @D4nte

**Comment by jm-clius** [comment]
May overlap with some goals in https://github.com/status-im/nim-waku/issues/827 as well.

**Comment by D4nte** [comment]
I'd add some documentation to use a letsencrypt certificate to secure the websocket connection.

**Comment by oskarth** [comment]
Great breakdown, thank you!

I wonder if we need precompiled binaries for the first step? I don't think Nimbus provided this in the initially stages (I still recompile it every release for my beacon chain node)

**Comment by jm-clius** [comment]
Changed milestone to Release 0.11 as we require people to run the fixes in 0.10 for an effective trial.

**Comment by jm-clius** [comment]
Operator trial successfully launched. Feedback being tracked in https://github.com/status-im/nwaku/issues/1208
