### ISSUE TITLE
Ambient Discovery Roadmap (incl Disc v5)

### ISSUE THREAD

**Issue by kaiserd** [status-im/nwaku#879]
This issue serves as an overview over Waku discv5 related action items. A discussion of these and future ideas can be found [here](https://forum.vac.dev/t/waku-v2-discv5-roadmap-discussion/121).
It also lists sub-issues tracking action items we either completed or are working on.
As some of these action items are research and specification tasks, the corresponding issues are in the [research](https://github.com/vacp2p/research) and [RFC](https://github.com/vacp2p/rfc) repositories, respectively.
Implementations are related to nim-waku if not stated otherwise.

## Action items 

* [x] implement: separate waku discv5 network via selectable protocol-id (#837)
* [x] ~raw~ draft RFC:   specify Waku2 ambient peer discovery protocol based on discv5 ([vacp2p/rfc #486](https://github.com/vacp2p/rfc/issues/486))
* [x] forum:     rough estimation of efficiency-loss due to needle-in-a-haystack problem ([forum](https://forum.vac.dev/t/waku-v2-discv5-roadmap-discussion/121/))
* [x] implement: discv5 bootstrap nodes via DNS (#880)

Edit: moved future tasks into https://github.com/vacp2p/research/issues/116, https://github.com/vacp2p/research/issues/117, https://github.com/vacp2p/research/issues/118
